version: '3.7'

services:
  spring_service:
    env_file:
      - .env
    build:
      context: ./trans-back
      args:
        - ENV=${ENV}
    container_name: spring-${ENV}
    ports:
      - "${PORT}:9090"
      - "12529:22"
#    stdin_open: true
#    command: bash
#    tty: true
